[2025-02-21T14:29:26.388+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer manual__2025-02-21T14:26:59.993378+00:00 [queued]>
[2025-02-21T14:29:26.459+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer manual__2025-02-21T14:26:59.993378+00:00 [queued]>
[2025-02-21T14:29:26.466+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-02-21T14:29:26.521+0000] {taskinstance.py:1382} INFO - Executing <Task(DockerOperator): pyspark_consumer> on 2025-02-21 14:26:59.993378+00:00
[2025-02-21T14:29:26.534+0000] {standard_task_runner.py:57} INFO - Started process 2055 to run task
[2025-02-21T14:29:26.547+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'kafka_spark_dag', 'pyspark_consumer', 'manual__2025-02-21T14:26:59.993378+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmpedjs7ix6']
[2025-02-21T14:29:26.549+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask pyspark_consumer
[2025-02-21T14:29:26.810+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.pyspark_consumer manual__2025-02-21T14:26:59.993378+00:00 [running]> on host 9240cfed0829
[2025-02-21T14:29:27.073+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='pyspark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T14:26:59.993378+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T14:26:59.993378+00:00'
[2025-02-21T14:29:27.170+0000] {docker.py:343} INFO - Starting docker container from image Mohamed/spark:latest
[2025-02-21T14:29:27.181+0000] {docker.py:351} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-02-21T14:29:28.333+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m14:29:28.32 [0m[38;5;2mINFO [0m ==>
[2025-02-21T14:29:28.369+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m14:29:28.35 [0m[38;5;2mINFO [0m ==> [1mWelcome to the Bitnami spark container[0m
[2025-02-21T14:29:28.379+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m14:29:28.37 [0m[38;5;2mINFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2025-02-21T14:29:28.404+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m14:29:28.39 [0m[38;5;2mINFO [0m ==> Submit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2025-02-21T14:29:28.420+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m14:29:28.41 [0m[38;5;2mINFO [0m ==>
[2025-02-21T14:29:28.567+0000] {docker.py:413} INFO - 
[2025-02-21T14:29:41.734+0000] {docker.py:413} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-02-21T14:29:42.039+0000] {docker.py:413} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2025-02-21T14:29:42.055+0000] {docker.py:413} INFO - org.postgresql#postgresql added as a dependency
[2025-02-21T14:29:42.059+0000] {docker.py:413} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-02-21T14:29:42.061+0000] {docker.py:413} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-0146af7a-6b32-46dc-afdd-0f76a80d92af;1.0
[2025-02-21T14:29:42.062+0000] {docker.py:413} INFO - confs: [default]
[2025-02-21T14:29:44.691+0000] {docker.py:413} INFO - found org.postgresql#postgresql;42.5.4 in central
[2025-02-21T14:29:44.945+0000] {docker.py:413} INFO - found org.checkerframework#checker-qual;3.5.0 in central
[2025-02-21T14:29:48.575+0000] {docker.py:413} INFO - found org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0 in central
[2025-02-21T14:29:49.524+0000] {docker.py:413} INFO - found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0 in central
[2025-02-21T14:29:49.801+0000] {docker.py:413} INFO - found org.apache.kafka#kafka-clients;3.4.1 in central
[2025-02-21T14:29:50.181+0000] {docker.py:413} INFO - found org.lz4#lz4-java;1.8.0 in central
[2025-02-21T14:29:50.649+0000] {docker.py:413} INFO - found org.xerial.snappy#snappy-java;1.1.10.3 in central
[2025-02-21T14:29:52.171+0000] {docker.py:413} INFO - found org.slf4j#slf4j-api;2.0.7 in central
[2025-02-21T14:29:54.613+0000] {docker.py:413} INFO - found org.apache.hadoop#hadoop-client-runtime;3.3.4 in central
[2025-02-21T14:29:55.160+0000] {docker.py:413} INFO - found org.apache.hadoop#hadoop-client-api;3.3.4 in central
[2025-02-21T14:29:57.353+0000] {docker.py:413} INFO - found commons-logging#commons-logging;1.1.3 in central
[2025-02-21T14:29:57.651+0000] {docker.py:413} INFO - found com.google.code.findbugs#jsr305;3.0.0 in central
[2025-02-21T14:30:00.790+0000] {docker.py:413} INFO - found org.apache.commons#commons-pool2;2.11.1 in central
[2025-02-21T14:30:00.911+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/postgresql/postgresql/42.5.4/postgresql-42.5.4.jar ...
[2025-02-21T14:30:01.421+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.postgresql#postgresql;42.5.4!postgresql.jar (562ms)
[2025-02-21T14:30:01.475+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.jar ...
[2025-02-21T14:30:01.662+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0!spark-sql-kafka-0-10_2.12.jar (239ms)
[2025-02-21T14:30:01.726+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.jar ...
[2025-02-21T14:30:01.888+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.checkerframework#checker-qual;3.5.0!checker-qual.jar (203ms)
[2025-02-21T14:30:01.968+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.0/spark-token-provider-kafka-0-10_2.12-3.5.0.jar ...
[2025-02-21T14:30:02.058+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0!spark-token-provider-kafka-0-10_2.12.jar (156ms)
[2025-02-21T14:30:02.121+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.4.1/kafka-clients-3.4.1.jar ...
[2025-02-21T14:30:03.581+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.kafka#kafka-clients;3.4.1!kafka-clients.jar (1516ms)
[2025-02-21T14:30:03.680+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar ...
[2025-02-21T14:30:03.770+0000] {docker.py:413} INFO - [SUCCESSFUL ] com.google.code.findbugs#jsr305;3.0.0!jsr305.jar (150ms)
[2025-02-21T14:30:03.828+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar ...
[2025-02-21T14:30:03.931+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.commons#commons-pool2;2.11.1!commons-pool2.jar (157ms)
[2025-02-21T14:30:03.990+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-runtime/3.3.4/hadoop-client-runtime-3.3.4.jar ...
[2025-02-21T14:30:12.348+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.hadoop#hadoop-client-runtime;3.3.4!hadoop-client-runtime.jar (8412ms)
[2025-02-21T14:30:12.418+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar ...
[2025-02-21T14:30:12.668+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.lz4#lz4-java;1.8.0!lz4-java.jar (302ms)
[2025-02-21T14:30:12.721+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.10.3/snappy-java-1.1.10.3.jar ...
[2025-02-21T14:30:13.537+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.xerial.snappy#snappy-java;1.1.10.3!snappy-java.jar(bundle) (863ms)
[2025-02-21T14:30:13.593+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar ...
[2025-02-21T14:30:13.714+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.slf4j#slf4j-api;2.0.7!slf4j-api.jar (177ms)
[2025-02-21T14:30:13.782+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-api/3.3.4/hadoop-client-api-3.3.4.jar ...
[2025-02-21T14:30:27.987+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.hadoop#hadoop-client-api;3.3.4!hadoop-client-api.jar (14269ms)
[2025-02-21T14:30:28.056+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar ...
[2025-02-21T14:30:28.126+0000] {docker.py:413} INFO - [SUCCESSFUL ] commons-logging#commons-logging;1.1.3!commons-logging.jar (134ms)
[2025-02-21T14:30:28.131+0000] {docker.py:413} INFO - :: resolution report :: resolve 18790ms :: artifacts dl 27281ms
	:: modules in use:
[2025-02-21T14:30:28.132+0000] {docker.py:413} INFO - com.google.code.findbugs#jsr305;3.0.0 from central in [default]
	commons-logging#commons-logging;1.1.3 from central in [default]
	org.apache.commons#commons-pool2;2.11.1 from central in [default]
	org.apache.hadoop#hadoop-client-api;3.3.4 from central in [default]
	org.apache.hadoop#hadoop-client-runtime;3.3.4 from central in [default]
	org.apache.kafka#kafka-clients;3.4.1 from central in [default]
	org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0 from central in [default]
[2025-02-21T14:30:28.136+0000] {docker.py:413} INFO - org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0 from central in [default]
	org.checkerframework#checker-qual;3.5.0 from central in [default]
	org.lz4#lz4-java;1.8.0 from central in [default]
	org.postgresql#postgresql;42.5.4 from central in [default]
	org.slf4j#slf4j-api;2.0.7 from central in [default]
	org.xerial.snappy#snappy-java;1.1.10.3 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   13  |   13  |   13  |   0   ||   13  |   13  |
	---------------------------------------------------------------------
[2025-02-21T14:30:28.157+0000] {docker.py:413} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-0146af7a-6b32-46dc-afdd-0f76a80d92af
[2025-02-21T14:30:28.162+0000] {docker.py:413} INFO - confs: [default]
[2025-02-21T14:30:28.513+0000] {docker.py:413} INFO - 13 artifacts copied, 0 already retrieved (58001kB/353ms)
[2025-02-21T14:30:29.721+0000] {docker.py:413} INFO - 25/02/21 14:30:29 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-02-21T14:30:34.943+0000] {docker.py:413} INFO - Traceback (most recent call last):
  File "/opt/bitnami/spark/spark_pgsql.py", line 4, in <module>
    sys.path.insert(0, '/opt/bitnami/spark/scripts')  # Ensure Spark finds constants.py
    ^^^
NameError: name 'sys' is not defined
[2025-02-21T14:30:35.111+0000] {docker.py:413} INFO - 25/02/21 14:30:35 INFO ShutdownHookManager: Shutdown hook called
[2025-02-21T14:30:35.116+0000] {docker.py:413} INFO - 25/02/21 14:30:35 INFO ShutdownHookManager: Deleting directory /tmp/spark-a7bcaee4-f147-445c-9ce0-59fbab784d4b
[2025-02-21T14:30:36.300+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker-proxy:2375/v1.48/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 348, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 375, in _run_image_with_mounts
    self.container = self.cli.create_container(
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/container.py", line 431, in create_container
    return self.create_container_from_config(config, name, platform)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/container.py", line 448, in create_container_from_config
    return self._result(res, True)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http://docker-proxy:2375/v1.48/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/airflowtmp98g7abt2")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 486, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 357, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 421, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-02-21T14:30:36.311+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=kafka_spark_dag, task_id=pyspark_consumer, execution_date=20250221T142659, start_date=20250221T142926, end_date=20250221T143036
[2025-02-21T14:30:36.347+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 42 for task pyspark_consumer (Docker container failed: {'StatusCode': 1}; 2055)
[2025-02-21T14:30:36.392+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-21T14:30:36.583+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
