[2025-02-21T14:27:59.650+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer manual__2025-02-21T14:26:59.993378+00:00 [queued]>
[2025-02-21T14:27:59.701+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer manual__2025-02-21T14:26:59.993378+00:00 [queued]>
[2025-02-21T14:27:59.703+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-21T14:27:59.741+0000] {taskinstance.py:1382} INFO - Executing <Task(DockerOperator): pyspark_consumer> on 2025-02-21 14:26:59.993378+00:00
[2025-02-21T14:27:59.773+0000] {standard_task_runner.py:57} INFO - Started process 1397 to run task
[2025-02-21T14:27:59.797+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'kafka_spark_dag', 'pyspark_consumer', 'manual__2025-02-21T14:26:59.993378+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmp6acglg8s']
[2025-02-21T14:27:59.803+0000] {standard_task_runner.py:85} INFO - Job 41: Subtask pyspark_consumer
[2025-02-21T14:28:00.766+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.pyspark_consumer manual__2025-02-21T14:26:59.993378+00:00 [running]> on host 9240cfed0829
[2025-02-21T14:28:00.998+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='pyspark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T14:26:59.993378+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T14:26:59.993378+00:00'
[2025-02-21T14:28:01.538+0000] {docker.py:343} INFO - Starting docker container from image Mohamed/spark:latest
[2025-02-21T14:28:01.549+0000] {docker.py:351} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-02-21T14:28:11.445+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m14:28:11.42 [0m[38;5;2mINFO [0m ==>
[2025-02-21T14:28:11.486+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m14:28:11.47 [0m[38;5;2mINFO [0m ==> [1mWelcome to the Bitnami spark container[0m
[2025-02-21T14:28:11.502+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m14:28:11.49 [0m[38;5;2mINFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2025-02-21T14:28:11.511+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m14:28:11.50 [0m[38;5;2mINFO [0m ==> Submit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2025-02-21T14:28:11.519+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m14:28:11.51 [0m[38;5;2mINFO [0m ==>
[2025-02-21T14:28:12.380+0000] {docker.py:413} INFO - 
[2025-02-21T14:28:33.000+0000] {docker.py:413} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-02-21T14:28:33.262+0000] {docker.py:413} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
[2025-02-21T14:28:33.263+0000] {docker.py:413} INFO - The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2025-02-21T14:28:33.282+0000] {docker.py:413} INFO - org.postgresql#postgresql added as a dependency
[2025-02-21T14:28:33.284+0000] {docker.py:413} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-02-21T14:28:33.286+0000] {docker.py:413} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-e7e1d441-1a91-428f-9007-26290681f8e4;1.0
[2025-02-21T14:28:33.288+0000] {docker.py:413} INFO - confs: [default]
[2025-02-21T14:28:34.928+0000] {docker.py:413} INFO - found org.postgresql#postgresql;42.5.4 in central
[2025-02-21T14:28:35.058+0000] {docker.py:413} INFO - found org.checkerframework#checker-qual;3.5.0 in central
[2025-02-21T14:28:37.196+0000] {docker.py:413} INFO - found org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0 in central
[2025-02-21T14:28:38.418+0000] {docker.py:413} INFO - found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0 in central
[2025-02-21T14:28:38.611+0000] {docker.py:413} INFO - found org.apache.kafka#kafka-clients;3.4.1 in central
[2025-02-21T14:28:38.762+0000] {docker.py:413} INFO - found org.lz4#lz4-java;1.8.0 in central
[2025-02-21T14:28:38.916+0000] {docker.py:413} INFO - found org.xerial.snappy#snappy-java;1.1.10.3 in central
[2025-02-21T14:28:39.973+0000] {docker.py:413} INFO - found org.slf4j#slf4j-api;2.0.7 in central
[2025-02-21T14:28:42.274+0000] {docker.py:413} INFO - found org.apache.hadoop#hadoop-client-runtime;3.3.4 in central
[2025-02-21T14:28:42.554+0000] {docker.py:413} INFO - found org.apache.hadoop#hadoop-client-api;3.3.4 in central
[2025-02-21T14:28:44.584+0000] {docker.py:413} INFO - found commons-logging#commons-logging;1.1.3 in central
[2025-02-21T14:28:44.792+0000] {docker.py:413} INFO - found com.google.code.findbugs#jsr305;3.0.0 in central
[2025-02-21T14:28:47.863+0000] {docker.py:413} INFO - found org.apache.commons#commons-pool2;2.11.1 in central
[2025-02-21T14:28:47.981+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/postgresql/postgresql/42.5.4/postgresql-42.5.4.jar ...
[2025-02-21T14:28:48.327+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.postgresql#postgresql;42.5.4!postgresql.jar (408ms)
[2025-02-21T14:28:48.383+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.jar ...
[2025-02-21T14:28:48.565+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0!spark-sql-kafka-0-10_2.12.jar (235ms)
[2025-02-21T14:28:48.629+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.jar ...
[2025-02-21T14:28:48.758+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.checkerframework#checker-qual;3.5.0!checker-qual.jar (181ms)
[2025-02-21T14:28:48.831+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.0/spark-token-provider-kafka-0-10_2.12-3.5.0.jar ...
[2025-02-21T14:28:48.912+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0!spark-token-provider-kafka-0-10_2.12.jar (132ms)
[2025-02-21T14:28:48.970+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.4.1/kafka-clients-3.4.1.jar ...
[2025-02-21T14:28:51.073+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.kafka#kafka-clients;3.4.1!kafka-clients.jar (2151ms)
[2025-02-21T14:28:51.144+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar ...
[2025-02-21T14:28:51.222+0000] {docker.py:413} INFO - [SUCCESSFUL ] com.google.code.findbugs#jsr305;3.0.0!jsr305.jar (148ms)
[2025-02-21T14:28:51.285+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar ...
[2025-02-21T14:28:51.380+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.commons#commons-pool2;2.11.1!commons-pool2.jar (151ms)
[2025-02-21T14:28:51.435+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-runtime/3.3.4/hadoop-client-runtime-3.3.4.jar ...
[2025-02-21T14:28:59.898+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.hadoop#hadoop-client-runtime;3.3.4!hadoop-client-runtime.jar (8512ms)
[2025-02-21T14:28:59.977+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar ...
[2025-02-21T14:29:00.290+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.lz4#lz4-java;1.8.0!lz4-java.jar (359ms)
[2025-02-21T14:29:00.366+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.10.3/snappy-java-1.1.10.3.jar ...
[2025-02-21T14:29:00.979+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.xerial.snappy#snappy-java;1.1.10.3!snappy-java.jar(bundle) (687ms)
[2025-02-21T14:29:01.045+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar ...
[2025-02-21T14:29:01.156+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.slf4j#slf4j-api;2.0.7!slf4j-api.jar (164ms)
[2025-02-21T14:29:01.219+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-api/3.3.4/hadoop-client-api-3.3.4.jar ...
[2025-02-21T14:29:07.699+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.hadoop#hadoop-client-api;3.3.4!hadoop-client-api.jar (6535ms)
[2025-02-21T14:29:07.750+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar ...
[2025-02-21T14:29:07.824+0000] {docker.py:413} INFO - [SUCCESSFUL ] commons-logging#commons-logging;1.1.3!commons-logging.jar (119ms)
[2025-02-21T14:29:07.827+0000] {docker.py:413} INFO - :: resolution report :: resolve 14626ms :: artifacts dl 19914ms
	:: modules in use:
[2025-02-21T14:29:07.829+0000] {docker.py:413} INFO - com.google.code.findbugs#jsr305;3.0.0 from central in [default]
	commons-logging#commons-logging;1.1.3 from central in [default]
	org.apache.commons#commons-pool2;2.11.1 from central in [default]
	org.apache.hadoop#hadoop-client-api;3.3.4 from central in [default]
	org.apache.hadoop#hadoop-client-runtime;3.3.4 from central in [default]
	org.apache.kafka#kafka-clients;3.4.1 from central in [default]
	org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0 from central in [default]
	org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0 from central in [default]
	org.checkerframework#checker-qual;3.5.0 from central in [default]
[2025-02-21T14:29:07.831+0000] {docker.py:413} INFO - org.lz4#lz4-java;1.8.0 from central in [default]
	org.postgresql#postgresql;42.5.4 from central in [default]
	org.slf4j#slf4j-api;2.0.7 from central in [default]
	org.xerial.snappy#snappy-java;1.1.10.3 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
[2025-02-21T14:29:07.832+0000] {docker.py:413} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   13  |   13  |   13  |   0   ||   13  |   13  |
	---------------------------------------------------------------------
[2025-02-21T14:29:07.868+0000] {docker.py:413} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-e7e1d441-1a91-428f-9007-26290681f8e4
[2025-02-21T14:29:07.869+0000] {docker.py:413} INFO - confs: [default]
[2025-02-21T14:29:08.054+0000] {docker.py:413} INFO - 13 artifacts copied, 0 already retrieved (58001kB/186ms)
[2025-02-21T14:29:09.019+0000] {docker.py:413} INFO - 25/02/21 14:29:09 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-02-21T14:29:14.990+0000] {docker.py:413} INFO - Traceback (most recent call last):
[2025-02-21T14:29:14.995+0000] {docker.py:413} INFO - File "/opt/bitnami/spark/spark_pgsql.py", line 4, in <module>
[2025-02-21T14:29:15.000+0000] {docker.py:413} INFO - 
[2025-02-21T14:29:15.001+0000] {docker.py:413} INFO - sys.path.insert(0, '/opt/bitnami/spark/scripts')  # Ensure Spark finds constants.py
[2025-02-21T14:29:15.002+0000] {docker.py:413} INFO - 
[2025-02-21T14:29:15.004+0000] {docker.py:413} INFO - 
[2025-02-21T14:29:15.004+0000] {docker.py:413} INFO - ^^^
NameError: name 'sys' is not defined
[2025-02-21T14:29:15.251+0000] {docker.py:413} INFO - 25/02/21 14:29:15 INFO ShutdownHookManager: Shutdown hook called
[2025-02-21T14:29:15.255+0000] {docker.py:413} INFO - 25/02/21 14:29:15 INFO ShutdownHookManager: Deleting directory /tmp/spark-901711ce-f3c2-46b6-a18a-247b56596567
[2025-02-21T14:29:15.842+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker-proxy:2375/v1.48/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 348, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 375, in _run_image_with_mounts
    self.container = self.cli.create_container(
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/container.py", line 431, in create_container
    return self.create_container_from_config(config, name, platform)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/container.py", line 448, in create_container_from_config
    return self._result(res, True)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http://docker-proxy:2375/v1.48/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/airflowtmpx8i1rjb_")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 486, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 357, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 421, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-02-21T14:29:15.861+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_spark_dag, task_id=pyspark_consumer, execution_date=20250221T142659, start_date=20250221T142759, end_date=20250221T142915
[2025-02-21T14:29:15.904+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 41 for task pyspark_consumer (Docker container failed: {'StatusCode': 1}; 1397)
[2025-02-21T14:29:15.986+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-21T14:29:16.040+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
