[2025-02-16T12:31:27.894+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer manual__2025-02-16T12:30:18.470884+00:00 [queued]>
[2025-02-16T12:31:27.926+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer manual__2025-02-16T12:30:18.470884+00:00 [queued]>
[2025-02-16T12:31:27.927+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-16T12:31:28.009+0000] {taskinstance.py:1382} INFO - Executing <Task(DockerOperator): pyspark_consumer> on 2025-02-16 12:30:18.470884+00:00
[2025-02-16T12:31:28.052+0000] {standard_task_runner.py:57} INFO - Started process 13677 to run task
[2025-02-16T12:31:28.093+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'kafka_spark_dag', 'pyspark_consumer', 'manual__2025-02-16T12:30:18.470884+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmp8la7b_gv']
[2025-02-16T12:31:28.096+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask pyspark_consumer
[2025-02-16T12:31:28.482+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.pyspark_consumer manual__2025-02-16T12:30:18.470884+00:00 [running]> on host 00de9d446011
[2025-02-16T12:31:28.934+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='pyspark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T12:30:18.470884+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-16T12:30:18.470884+00:00'
[2025-02-16T12:31:29.190+0000] {docker.py:343} INFO - Starting docker container from image Mohamed/spark:latest
[2025-02-16T12:31:29.250+0000] {docker.py:351} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-02-16T12:31:32.311+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m12:31:32.29 [0m[38;5;2mINFO [0m ==>
[2025-02-16T12:31:32.350+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m12:31:32.33 [0m[38;5;2mINFO [0m ==> [1mWelcome to the Bitnami spark container[0m
[2025-02-16T12:31:32.370+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m12:31:32.36 [0m[38;5;2mINFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2025-02-16T12:31:32.401+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m12:31:32.38 [0m[38;5;2mINFO [0m ==> Submit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2025-02-16T12:31:32.419+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m12:31:32.41 [0m[38;5;2mINFO [0m ==>
[2025-02-16T12:31:32.540+0000] {docker.py:413} INFO - 
[2025-02-16T12:31:59.707+0000] {docker.py:413} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-02-16T12:32:01.072+0000] {docker.py:413} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2025-02-16T12:32:01.141+0000] {docker.py:413} INFO - org.postgresql#postgresql added as a dependency
org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-02-16T12:32:01.149+0000] {docker.py:413} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-f613ed13-e6f0-40f2-a2b7-4aec4edcabdb;1.0
[2025-02-16T12:32:01.153+0000] {docker.py:413} INFO - confs: [default]
[2025-02-16T12:32:05.988+0000] {docker.py:413} INFO - found org.postgresql#postgresql;42.5.4 in central
[2025-02-16T12:32:06.451+0000] {docker.py:413} INFO - found org.checkerframework#checker-qual;3.5.0 in central
[2025-02-16T12:32:12.936+0000] {docker.py:413} INFO - found org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0 in central
[2025-02-16T12:32:18.171+0000] {docker.py:413} INFO - found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0 in central
[2025-02-16T12:32:18.433+0000] {docker.py:413} INFO - found org.apache.kafka#kafka-clients;3.4.1 in central
[2025-02-16T12:32:18.740+0000] {docker.py:413} INFO - found org.lz4#lz4-java;1.8.0 in central
[2025-02-16T12:32:19.579+0000] {docker.py:413} INFO - found org.xerial.snappy#snappy-java;1.1.10.3 in central
[2025-02-16T12:32:21.998+0000] {docker.py:413} INFO - found org.slf4j#slf4j-api;2.0.7 in central
[2025-02-16T12:32:26.409+0000] {docker.py:413} INFO - found org.apache.hadoop#hadoop-client-runtime;3.3.4 in central
[2025-02-16T12:32:27.794+0000] {docker.py:413} INFO - found org.apache.hadoop#hadoop-client-api;3.3.4 in central
[2025-02-16T12:32:30.412+0000] {docker.py:413} INFO - found commons-logging#commons-logging;1.1.3 in central
[2025-02-16T12:32:30.758+0000] {docker.py:413} INFO - found com.google.code.findbugs#jsr305;3.0.0 in central
[2025-02-16T12:32:34.636+0000] {docker.py:413} INFO - found org.apache.commons#commons-pool2;2.11.1 in central
[2025-02-16T12:32:35.206+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/postgresql/postgresql/42.5.4/postgresql-42.5.4.jar ...
[2025-02-16T12:32:35.886+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.postgresql#postgresql;42.5.4!postgresql.jar (759ms)
[2025-02-16T12:32:36.073+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.jar ...
[2025-02-16T12:32:37.171+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0!spark-sql-kafka-0-10_2.12.jar (1255ms)
[2025-02-16T12:32:37.336+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.jar ...
[2025-02-16T12:32:37.573+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.checkerframework#checker-qual;3.5.0!checker-qual.jar (338ms)
[2025-02-16T12:32:37.775+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.0/spark-token-provider-kafka-0-10_2.12-3.5.0.jar ...
[2025-02-16T12:32:37.921+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0!spark-token-provider-kafka-0-10_2.12.jar (304ms)
[2025-02-16T12:32:38.025+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.4.1/kafka-clients-3.4.1.jar ...
[2025-02-16T12:32:39.814+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.kafka#kafka-clients;3.4.1!kafka-clients.jar (1843ms)
[2025-02-16T12:32:39.888+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar ...
[2025-02-16T12:32:39.966+0000] {docker.py:413} INFO - [SUCCESSFUL ] com.google.code.findbugs#jsr305;3.0.0!jsr305.jar (137ms)
[2025-02-16T12:32:40.019+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar ...
[2025-02-16T12:32:40.136+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.commons#commons-pool2;2.11.1!commons-pool2.jar (169ms)
[2025-02-16T12:32:40.201+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-runtime/3.3.4/hadoop-client-runtime-3.3.4.jar ...
[2025-02-16T12:32:54.349+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.hadoop#hadoop-client-runtime;3.3.4!hadoop-client-runtime.jar (14203ms)
[2025-02-16T12:32:54.410+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar ...
[2025-02-16T12:32:54.712+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.lz4#lz4-java;1.8.0!lz4-java.jar (356ms)
[2025-02-16T12:32:54.786+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.10.3/snappy-java-1.1.10.3.jar ...
[2025-02-16T12:32:55.661+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.xerial.snappy#snappy-java;1.1.10.3!snappy-java.jar(bundle) (937ms)
[2025-02-16T12:32:55.728+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar ...
[2025-02-16T12:32:55.822+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.slf4j#slf4j-api;2.0.7!slf4j-api.jar (151ms)
[2025-02-16T12:32:55.906+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-api/3.3.4/hadoop-client-api-3.3.4.jar ...
[2025-02-16T12:33:08.897+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.hadoop#hadoop-client-api;3.3.4!hadoop-client-api.jar (13028ms)
[2025-02-16T12:33:09.005+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar ...
[2025-02-16T12:33:09.161+0000] {docker.py:413} INFO - [SUCCESSFUL ] commons-logging#commons-logging;1.1.3!commons-logging.jar (217ms)
[2025-02-16T12:33:09.165+0000] {docker.py:413} INFO - :: resolution report :: resolve 33951ms :: artifacts dl 34062ms
[2025-02-16T12:33:09.170+0000] {docker.py:413} INFO - :: modules in use:
[2025-02-16T12:33:09.171+0000] {docker.py:413} INFO - com.google.code.findbugs#jsr305;3.0.0 from central in [default]
[2025-02-16T12:33:09.171+0000] {docker.py:413} INFO - commons-logging#commons-logging;1.1.3 from central in [default]
	org.apache.commons#commons-pool2;2.11.1 from central in [default]
	org.apache.hadoop#hadoop-client-api;3.3.4 from central in [default]
	org.apache.hadoop#hadoop-client-runtime;3.3.4 from central in [default]
[2025-02-16T12:33:09.172+0000] {docker.py:413} INFO - org.apache.kafka#kafka-clients;3.4.1 from central in [default]
[2025-02-16T12:33:09.177+0000] {docker.py:413} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0 from central in [default]
	org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0 from central in [default]
	org.checkerframework#checker-qual;3.5.0 from central in [default]
	org.lz4#lz4-java;1.8.0 from central in [default]
	org.postgresql#postgresql;42.5.4 from central in [default]
	org.slf4j#slf4j-api;2.0.7 from central in [default]
	org.xerial.snappy#snappy-java;1.1.10.3 from central in [default]
[2025-02-16T12:33:09.199+0000] {docker.py:413} INFO - ---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   13  |   13  |   13  |   0   ||   13  |   13  |
	---------------------------------------------------------------------
[2025-02-16T12:33:09.313+0000] {docker.py:413} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-f613ed13-e6f0-40f2-a2b7-4aec4edcabdb
[2025-02-16T12:33:09.313+0000] {docker.py:413} INFO - confs: [default]
[2025-02-16T12:33:09.906+0000] {docker.py:413} INFO - 13 artifacts copied, 0 already retrieved (58001kB/594ms)
[2025-02-16T12:33:15.322+0000] {docker.py:413} INFO - 25/02/16 12:33:15 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-02-16T12:33:28.893+0000] {docker.py:413} INFO - Traceback (most recent call last):
  File "/opt/bitnami/spark/spark_pgsql.py", line 4, in <module>
    from constants import (
ModuleNotFoundError: No module named 'constants'
[2025-02-16T12:33:29.200+0000] {docker.py:413} INFO - 25/02/16 12:33:29 INFO ShutdownHookManager: Shutdown hook called
[2025-02-16T12:33:29.205+0000] {docker.py:413} INFO - 25/02/16 12:33:29 INFO ShutdownHookManager: Deleting directory /tmp/spark-4b3c2518-6f78-47f2-a394-61e95ae1e57c
[2025-02-16T12:33:30.271+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker-proxy:2375/v1.47/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 348, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 375, in _run_image_with_mounts
    self.container = self.cli.create_container(
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/container.py", line 431, in create_container
    return self.create_container_from_config(config, name, platform)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/container.py", line 448, in create_container_from_config
    return self._result(res, True)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http://docker-proxy:2375/v1.47/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/airflowtmpmark7bfl")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 486, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 357, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 421, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-02-16T12:33:30.334+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_spark_dag, task_id=pyspark_consumer, execution_date=20250216T123018, start_date=20250216T123127, end_date=20250216T123330
[2025-02-16T12:33:30.431+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 21 for task pyspark_consumer (Docker container failed: {'StatusCode': 1}; 13677)
[2025-02-16T12:33:30.525+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-16T12:33:30.665+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
