[2025-02-21T14:15:48.345+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer manual__2025-02-21T14:14:56.972465+00:00 [queued]>
[2025-02-21T14:15:48.376+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer manual__2025-02-21T14:14:56.972465+00:00 [queued]>
[2025-02-21T14:15:48.378+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-21T14:15:48.416+0000] {taskinstance.py:1382} INFO - Executing <Task(DockerOperator): pyspark_consumer> on 2025-02-21 14:14:56.972465+00:00
[2025-02-21T14:15:48.433+0000] {standard_task_runner.py:57} INFO - Started process 19489 to run task
[2025-02-21T14:15:48.446+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'kafka_spark_dag', 'pyspark_consumer', 'manual__2025-02-21T14:14:56.972465+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmp9aqkl0d7']
[2025-02-21T14:15:48.450+0000] {standard_task_runner.py:85} INFO - Job 37: Subtask pyspark_consumer
[2025-02-21T14:15:48.631+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.pyspark_consumer manual__2025-02-21T14:14:56.972465+00:00 [running]> on host d5862e138d8d
[2025-02-21T14:15:48.983+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='pyspark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T14:14:56.972465+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T14:14:56.972465+00:00'
[2025-02-21T14:15:49.218+0000] {docker.py:343} INFO - Starting docker container from image Mohamed/spark:latest
[2025-02-21T14:15:49.292+0000] {docker.py:351} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-02-21T14:15:50.502+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m14:15:50.49 [0m[38;5;2mINFO [0m ==>
[2025-02-21T14:15:50.510+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m14:15:50.50 [0m[38;5;2mINFO [0m ==> [1mWelcome to the Bitnami spark container[0m
[2025-02-21T14:15:50.517+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m14:15:50.51 [0m[38;5;2mINFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2025-02-21T14:15:50.537+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m14:15:50.53 [0m[38;5;2mINFO [0m ==> Submit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2025-02-21T14:15:50.571+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m14:15:50.56 [0m[38;5;2mINFO [0m ==>
[2025-02-21T14:15:50.678+0000] {docker.py:413} INFO - 
[2025-02-21T14:16:05.459+0000] {docker.py:413} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-02-21T14:16:06.098+0000] {docker.py:413} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2025-02-21T14:16:06.125+0000] {docker.py:413} INFO - org.postgresql#postgresql added as a dependency
[2025-02-21T14:16:06.127+0000] {docker.py:413} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-02-21T14:16:06.131+0000] {docker.py:413} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-95850fd3-cbea-4361-bc3f-39da7b47593b;1.0
	confs: [default]
[2025-02-21T14:16:08.628+0000] {docker.py:413} INFO - found org.postgresql#postgresql;42.5.4 in central
[2025-02-21T14:16:09.089+0000] {docker.py:413} INFO - found org.checkerframework#checker-qual;3.5.0 in central
[2025-02-21T14:16:12.362+0000] {docker.py:413} INFO - found org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0 in central
[2025-02-21T14:16:13.714+0000] {docker.py:413} INFO - found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0 in central
[2025-02-21T14:16:13.971+0000] {docker.py:413} INFO - found org.apache.kafka#kafka-clients;3.4.1 in central
[2025-02-21T14:16:14.208+0000] {docker.py:413} INFO - found org.lz4#lz4-java;1.8.0 in central
[2025-02-21T14:16:14.378+0000] {docker.py:413} INFO - found org.xerial.snappy#snappy-java;1.1.10.3 in central
[2025-02-21T14:16:15.581+0000] {docker.py:413} INFO - found org.slf4j#slf4j-api;2.0.7 in central
[2025-02-21T14:16:17.760+0000] {docker.py:413} INFO - found org.apache.hadoop#hadoop-client-runtime;3.3.4 in central
[2025-02-21T14:16:18.289+0000] {docker.py:413} INFO - found org.apache.hadoop#hadoop-client-api;3.3.4 in central
[2025-02-21T14:16:19.795+0000] {docker.py:413} INFO - found commons-logging#commons-logging;1.1.3 in central
[2025-02-21T14:16:19.945+0000] {docker.py:413} INFO - found com.google.code.findbugs#jsr305;3.0.0 in central
[2025-02-21T14:16:22.645+0000] {docker.py:413} INFO - found org.apache.commons#commons-pool2;2.11.1 in central
[2025-02-21T14:16:22.746+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/postgresql/postgresql/42.5.4/postgresql-42.5.4.jar ...
[2025-02-21T14:16:23.077+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.postgresql#postgresql;42.5.4!postgresql.jar (379ms)
[2025-02-21T14:16:23.129+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.jar ...
[2025-02-21T14:16:23.296+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0!spark-sql-kafka-0-10_2.12.jar (214ms)
[2025-02-21T14:16:23.346+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.jar ...
[2025-02-21T14:16:23.456+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.checkerframework#checker-qual;3.5.0!checker-qual.jar (157ms)
[2025-02-21T14:16:23.508+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.0/spark-token-provider-kafka-0-10_2.12-3.5.0.jar ...
[2025-02-21T14:16:23.576+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0!spark-token-provider-kafka-0-10_2.12.jar (117ms)
[2025-02-21T14:16:23.637+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.4.1/kafka-clients-3.4.1.jar ...
[2025-02-21T14:16:25.076+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.kafka#kafka-clients;3.4.1!kafka-clients.jar (1495ms)
[2025-02-21T14:16:25.127+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar ...
[2025-02-21T14:16:25.184+0000] {docker.py:413} INFO - [SUCCESSFUL ] com.google.code.findbugs#jsr305;3.0.0!jsr305.jar (105ms)
[2025-02-21T14:16:25.237+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar ...
[2025-02-21T14:16:25.334+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.commons#commons-pool2;2.11.1!commons-pool2.jar (146ms)
[2025-02-21T14:16:25.388+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-runtime/3.3.4/hadoop-client-runtime-3.3.4.jar ...
[2025-02-21T14:16:46.224+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.hadoop#hadoop-client-runtime;3.3.4!hadoop-client-runtime.jar (20884ms)
[2025-02-21T14:16:46.297+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar ...
[2025-02-21T14:16:46.536+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.lz4#lz4-java;1.8.0!lz4-java.jar (304ms)
[2025-02-21T14:16:46.594+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.10.3/snappy-java-1.1.10.3.jar ...
[2025-02-21T14:16:47.219+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.xerial.snappy#snappy-java;1.1.10.3!snappy-java.jar(bundle) (669ms)
[2025-02-21T14:16:47.284+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar ...
[2025-02-21T14:16:47.377+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.slf4j#slf4j-api;2.0.7!slf4j-api.jar (148ms)
[2025-02-21T14:16:47.448+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-api/3.3.4/hadoop-client-api-3.3.4.jar ...
[2025-02-21T14:16:53.000+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.hadoop#hadoop-client-api;3.3.4!hadoop-client-api.jar (5619ms)
[2025-02-21T14:16:53.052+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar ...
[2025-02-21T14:16:53.133+0000] {docker.py:413} INFO - [SUCCESSFUL ] commons-logging#commons-logging;1.1.3!commons-logging.jar (133ms)
[2025-02-21T14:16:53.139+0000] {docker.py:413} INFO - :: resolution report :: resolve 16560ms :: artifacts dl 30448ms
[2025-02-21T14:16:53.141+0000] {docker.py:413} INFO - :: modules in use:
[2025-02-21T14:16:53.144+0000] {docker.py:413} INFO - com.google.code.findbugs#jsr305;3.0.0 from central in [default]
[2025-02-21T14:16:53.146+0000] {docker.py:413} INFO - commons-logging#commons-logging;1.1.3 from central in [default]
[2025-02-21T14:16:53.150+0000] {docker.py:413} INFO - org.apache.commons#commons-pool2;2.11.1 from central in [default]
[2025-02-21T14:16:53.152+0000] {docker.py:413} INFO - org.apache.hadoop#hadoop-client-api;3.3.4 from central in [default]
[2025-02-21T14:16:53.154+0000] {docker.py:413} INFO - org.apache.hadoop#hadoop-client-runtime;3.3.4 from central in [default]
[2025-02-21T14:16:53.158+0000] {docker.py:413} INFO - org.apache.kafka#kafka-clients;3.4.1 from central in [default]
[2025-02-21T14:16:53.161+0000] {docker.py:413} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0 from central in [default]
[2025-02-21T14:16:53.167+0000] {docker.py:413} INFO - org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0 from central in [default]
[2025-02-21T14:16:53.167+0000] {docker.py:413} INFO - org.checkerframework#checker-qual;3.5.0 from central in [default]
[2025-02-21T14:16:53.175+0000] {docker.py:413} INFO - org.lz4#lz4-java;1.8.0 from central in [default]
[2025-02-21T14:16:53.176+0000] {docker.py:413} INFO - org.postgresql#postgresql;42.5.4 from central in [default]
	org.slf4j#slf4j-api;2.0.7 from central in [default]
	org.xerial.snappy#snappy-java;1.1.10.3 from central in [default]
	---------------------------------------------------------------------
[2025-02-21T14:16:53.179+0000] {docker.py:413} INFO - |                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
[2025-02-21T14:16:53.184+0000] {docker.py:413} INFO - |      default     |   13  |   13  |   13  |   0   ||   13  |   13  |
[2025-02-21T14:16:53.190+0000] {docker.py:413} INFO - ---------------------------------------------------------------------
[2025-02-21T14:16:53.271+0000] {docker.py:413} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-95850fd3-cbea-4361-bc3f-39da7b47593b
[2025-02-21T14:16:53.274+0000] {docker.py:413} INFO - confs: [default]
[2025-02-21T14:16:53.544+0000] {docker.py:413} INFO - 13 artifacts copied, 0 already retrieved (58001kB/273ms)
[2025-02-21T14:16:54.653+0000] {docker.py:413} INFO - 25/02/21 14:16:54 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-02-21T14:17:00.769+0000] {docker.py:413} INFO - Traceback (most recent call last):
  File "/opt/bitnami/spark/spark_pgsql.py", line 4, in <module>
    sys.path.insert(0, '/opt/bitnami/spark/scripts')  # Ensure Spark finds constants.py
    ^^^
NameError: name 'sys' is not defined
[2025-02-21T14:17:00.921+0000] {docker.py:413} INFO - 25/02/21 14:17:00 INFO ShutdownHookManager: Shutdown hook called
[2025-02-21T14:17:00.925+0000] {docker.py:413} INFO - 25/02/21 14:17:00 INFO ShutdownHookManager: Deleting directory /tmp/spark-6c0d9002-dcd1-4460-8bf4-05c6ed1f6ce7
[2025-02-21T14:17:02.062+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker-proxy:2375/v1.48/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 348, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 375, in _run_image_with_mounts
    self.container = self.cli.create_container(
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/container.py", line 431, in create_container
    return self.create_container_from_config(config, name, platform)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/container.py", line 448, in create_container_from_config
    return self._result(res, True)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http://docker-proxy:2375/v1.48/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/airflowtmprfun4wa5")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 486, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 357, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 421, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-02-21T14:17:02.108+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_spark_dag, task_id=pyspark_consumer, execution_date=20250221T141456, start_date=20250221T141548, end_date=20250221T141702
[2025-02-21T14:17:02.199+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 37 for task pyspark_consumer (Docker container failed: {'StatusCode': 1}; 19489)
[2025-02-21T14:17:02.274+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-21T14:17:02.381+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
