[2025-02-16T12:25:43.460+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer manual__2025-02-16T12:25:16.331175+00:00 [queued]>
[2025-02-16T12:25:43.562+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer manual__2025-02-16T12:25:16.331175+00:00 [queued]>
[2025-02-16T12:25:43.567+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-16T12:25:43.678+0000] {taskinstance.py:1382} INFO - Executing <Task(DockerOperator): pyspark_consumer> on 2025-02-16 12:25:16.331175+00:00
[2025-02-16T12:25:43.713+0000] {standard_task_runner.py:57} INFO - Started process 10982 to run task
[2025-02-16T12:25:43.736+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'kafka_spark_dag', 'pyspark_consumer', 'manual__2025-02-16T12:25:16.331175+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmp9ucz5z7t']
[2025-02-16T12:25:43.739+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask pyspark_consumer
[2025-02-16T12:25:44.068+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.pyspark_consumer manual__2025-02-16T12:25:16.331175+00:00 [running]> on host 00de9d446011
[2025-02-16T12:25:44.369+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='pyspark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T12:25:16.331175+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-16T12:25:16.331175+00:00'
[2025-02-16T12:25:44.542+0000] {docker.py:343} INFO - Starting docker container from image Mohamed/spark:latest
[2025-02-16T12:25:44.558+0000] {docker.py:351} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-02-16T12:25:47.206+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m12:25:47.19 [0m[38;5;2mINFO [0m ==>
[2025-02-16T12:25:47.215+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m12:25:47.20 [0m[38;5;2mINFO [0m ==> [1mWelcome to the Bitnami spark container[0m
[2025-02-16T12:25:47.227+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m12:25:47.22 [0m[38;5;2mINFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2025-02-16T12:25:47.235+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m12:25:47.22 [0m[38;5;2mINFO [0m ==> Submit issues and feature requests at [1mhttps://github.com/bitnami/containers/issues[0m
[2025-02-16T12:25:47.236+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m12:25:47.23 [0m[38;5;2mINFO [0m ==>
[2025-02-16T12:25:47.261+0000] {docker.py:413} INFO - 
[2025-02-16T12:26:20.784+0000] {docker.py:413} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-02-16T12:26:21.481+0000] {docker.py:413} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
[2025-02-16T12:26:21.485+0000] {docker.py:413} INFO - The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2025-02-16T12:26:21.526+0000] {docker.py:413} INFO - org.postgresql#postgresql added as a dependency
[2025-02-16T12:26:21.538+0000] {docker.py:413} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-02-16T12:26:21.552+0000] {docker.py:413} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-48531b62-b769-4f96-9ad7-5ff2e56281b9;1.0
[2025-02-16T12:26:21.554+0000] {docker.py:413} INFO - confs: [default]
[2025-02-16T12:26:30.964+0000] {docker.py:413} INFO - found org.postgresql#postgresql;42.5.4 in central
[2025-02-16T12:26:31.189+0000] {docker.py:413} INFO - found org.checkerframework#checker-qual;3.5.0 in central
[2025-02-16T12:26:34.103+0000] {docker.py:413} INFO - found org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0 in central
[2025-02-16T12:26:36.407+0000] {docker.py:413} INFO - found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0 in central
[2025-02-16T12:26:36.766+0000] {docker.py:413} INFO - found org.apache.kafka#kafka-clients;3.4.1 in central
[2025-02-16T12:26:37.184+0000] {docker.py:413} INFO - found org.lz4#lz4-java;1.8.0 in central
[2025-02-16T12:26:37.777+0000] {docker.py:413} INFO - found org.xerial.snappy#snappy-java;1.1.10.3 in central
[2025-02-16T12:26:38.834+0000] {docker.py:413} INFO - found org.slf4j#slf4j-api;2.0.7 in central
[2025-02-16T12:26:40.788+0000] {docker.py:413} INFO - found org.apache.hadoop#hadoop-client-runtime;3.3.4 in central
[2025-02-16T12:26:42.974+0000] {docker.py:413} INFO - found org.apache.hadoop#hadoop-client-api;3.3.4 in central
[2025-02-16T12:26:45.750+0000] {docker.py:413} INFO - found commons-logging#commons-logging;1.1.3 in central
[2025-02-16T12:26:46.258+0000] {docker.py:413} INFO - found com.google.code.findbugs#jsr305;3.0.0 in central
[2025-02-16T12:26:48.817+0000] {docker.py:413} INFO - found org.apache.commons#commons-pool2;2.11.1 in central
[2025-02-16T12:26:48.980+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/postgresql/postgresql/42.5.4/postgresql-42.5.4.jar ...
[2025-02-16T12:26:49.776+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.postgresql#postgresql;42.5.4!postgresql.jar (847ms)
[2025-02-16T12:26:49.843+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.jar ...
[2025-02-16T12:26:50.114+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0!spark-sql-kafka-0-10_2.12.jar (329ms)
[2025-02-16T12:26:50.158+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.jar ...
[2025-02-16T12:26:50.291+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.checkerframework#checker-qual;3.5.0!checker-qual.jar (176ms)
[2025-02-16T12:26:50.364+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.0/spark-token-provider-kafka-0-10_2.12-3.5.0.jar ...
[2025-02-16T12:26:50.461+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0!spark-token-provider-kafka-0-10_2.12.jar (164ms)
[2025-02-16T12:26:50.533+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.4.1/kafka-clients-3.4.1.jar ...
[2025-02-16T12:26:53.185+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.kafka#kafka-clients;3.4.1!kafka-clients.jar (2704ms)
[2025-02-16T12:26:53.262+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar ...
[2025-02-16T12:26:53.330+0000] {docker.py:413} INFO - [SUCCESSFUL ] com.google.code.findbugs#jsr305;3.0.0!jsr305.jar (123ms)
[2025-02-16T12:26:53.389+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar ...
[2025-02-16T12:26:53.543+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.commons#commons-pool2;2.11.1!commons-pool2.jar (212ms)
[2025-02-16T12:26:53.619+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-runtime/3.3.4/hadoop-client-runtime-3.3.4.jar ...
[2025-02-16T12:27:11.257+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.hadoop#hadoop-client-runtime;3.3.4!hadoop-client-runtime.jar (17698ms)
[2025-02-16T12:27:11.325+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar ...
[2025-02-16T12:27:11.783+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.lz4#lz4-java;1.8.0!lz4-java.jar (520ms)
[2025-02-16T12:27:11.855+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.10.3/snappy-java-1.1.10.3.jar ...
[2025-02-16T12:27:13.279+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.xerial.snappy#snappy-java;1.1.10.3!snappy-java.jar(bundle) (1475ms)
[2025-02-16T12:27:13.417+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar ...
[2025-02-16T12:27:13.515+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.slf4j#slf4j-api;2.0.7!slf4j-api.jar (230ms)
[2025-02-16T12:27:13.569+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-api/3.3.4/hadoop-client-api-3.3.4.jar ...
[2025-02-16T12:27:22.355+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.hadoop#hadoop-client-api;3.3.4!hadoop-client-api.jar (8833ms)
[2025-02-16T12:27:22.415+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar ...
[2025-02-16T12:27:22.517+0000] {docker.py:413} INFO - [SUCCESSFUL ] commons-logging#commons-logging;1.1.3!commons-logging.jar (153ms)
[2025-02-16T12:27:22.525+0000] {docker.py:413} INFO - :: resolution report :: resolve 27366ms :: artifacts dl 33609ms
[2025-02-16T12:27:22.529+0000] {docker.py:413} INFO - :: modules in use:
	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
[2025-02-16T12:27:22.533+0000] {docker.py:413} INFO - commons-logging#commons-logging;1.1.3 from central in [default]
	org.apache.commons#commons-pool2;2.11.1 from central in [default]
[2025-02-16T12:27:22.535+0000] {docker.py:413} INFO - org.apache.hadoop#hadoop-client-api;3.3.4 from central in [default]
[2025-02-16T12:27:22.538+0000] {docker.py:413} INFO - org.apache.hadoop#hadoop-client-runtime;3.3.4 from central in [default]
[2025-02-16T12:27:22.541+0000] {docker.py:413} INFO - org.apache.kafka#kafka-clients;3.4.1 from central in [default]
[2025-02-16T12:27:22.544+0000] {docker.py:413} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0 from central in [default]
[2025-02-16T12:27:22.548+0000] {docker.py:413} INFO - org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0 from central in [default]
[2025-02-16T12:27:22.552+0000] {docker.py:413} INFO - org.checkerframework#checker-qual;3.5.0 from central in [default]
	org.lz4#lz4-java;1.8.0 from central in [default]
	org.postgresql#postgresql;42.5.4 from central in [default]
	org.slf4j#slf4j-api;2.0.7 from central in [default]
	org.xerial.snappy#snappy-java;1.1.10.3 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   13  |   13  |   13  |   0   ||   13  |   13  |
	---------------------------------------------------------------------
[2025-02-16T12:27:22.603+0000] {docker.py:413} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-48531b62-b769-4f96-9ad7-5ff2e56281b9
[2025-02-16T12:27:22.610+0000] {docker.py:413} INFO - confs: [default]
[2025-02-16T12:27:23.183+0000] {docker.py:413} INFO - 13 artifacts copied, 0 already retrieved (58001kB/580ms)
[2025-02-16T12:27:27.237+0000] {docker.py:413} INFO - 25/02/16 12:27:27 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-02-16T12:27:33.027+0000] {docker.py:413} INFO - python3: can't open file '/opt/bitnami/spark/spark_streaming.py': [Errno 2] No such file or directory
[2025-02-16T12:27:33.162+0000] {docker.py:413} INFO - 25/02/16 12:27:33 INFO ShutdownHookManager: Shutdown hook called
[2025-02-16T12:27:33.170+0000] {docker.py:413} INFO - 25/02/16 12:27:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-44a590bb-ca86-4568-8516-fa317bf0cce0
[2025-02-16T12:27:34.129+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker-proxy:2375/v1.47/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 348, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 375, in _run_image_with_mounts
    self.container = self.cli.create_container(
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/container.py", line 431, in create_container
    return self.create_container_from_config(config, name, platform)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/container.py", line 448, in create_container_from_config
    return self._result(res, True)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http://docker-proxy:2375/v1.47/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/airflowtmpipo3ga36")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 486, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 357, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 421, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 2}
[2025-02-16T12:27:34.154+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_spark_dag, task_id=pyspark_consumer, execution_date=20250216T122516, start_date=20250216T122543, end_date=20250216T122734
[2025-02-16T12:27:34.212+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task pyspark_consumer (Docker container failed: {'StatusCode': 2}; 10982)
[2025-02-16T12:27:34.249+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-16T12:27:34.328+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
